DO $$
DECLARE account uuid; foreign_account uuid; payroll_id uuid; bonus_id uuid; r payroll_record; settings jsonb;
  travel jsonb; total numeric; linked uuid; before_revision integer; n integer;
BEGIN
  INSERT INTO "user" VALUES ('salary-owner'), ('salary-other');
  INSERT INTO financial_account(user_id) VALUES ('salary-owner') RETURNING id INTO account;
  INSERT INTO financial_account(user_id) VALUES ('salary-other') RETURNING id INTO foreign_account;
  settings := '{"grossCents":175000,"mealCents":13000,"ssRate":1100,"tsuRate":2375,"irsRate":1303,"irsOverrideCents":22800}';
  INSERT INTO salary_settings(user_id, gross_cents, account_id) VALUES ('salary-owner', 175000, account);
  INSERT INTO journey(user_id, date, distance) VALUES ('salary-owner', '2026-09-01', 100), ('salary-owner', '2026-09-30', 120), ('salary-owner', '2026-10-01', 150), ('salary-other', '2026-09-01', 999);
  INSERT INTO per_diem(user_id, date, daily_rate_cents, percentage) VALUES ('salary-owner', '2026-09-01', 7265, 25), ('salary-owner', '2026-09-02', 7265, 100), ('salary-other', '2026-09-01', 99999, 100);
  travel := '{"perDiemCents":9081,"mileageCents":8800}';
  payroll_id := payroll_generate('salary-owner', '2026-09', 'monthly', settings, travel);
  SELECT * INTO r FROM payroll_record WHERE id = payroll_id;
  ASSERT r.per_diem_cents = 9081 AND r.mileage_cents = 8800 AND r.kilometres = 220 AND r.per_diem_days = 2, 'Travel inclusion, period or ownership';
  ASSERT r.ss_cents = 19250 AND r.tsu_cents = 41563 AND r.irs_cents = 22800, 'Contributions';
  ASSERT r.net_cents = 163831 AND r.company_cents = 247444, 'Net/company amounts';
  ASSERT (SELECT count(*) FROM expense) = 0, 'Generation must not create expenses';
  BEGIN PERFORM payroll_generate('salary-owner', '2026-09', 'monthly', settings, travel); RAISE EXCEPTION 'FAIL duplicate'; EXCEPTION WHEN unique_violation THEN NULL; END;
  BEGIN INSERT INTO journey(user_id, date, distance) VALUES ('salary-owner', '2026-09-10', 10); RAISE EXCEPTION 'FAIL closed trip'; EXCEPTION WHEN raise_exception THEN ASSERT SQLERRM LIKE 'This month is closed%', SQLERRM; END;
  BEGIN UPDATE per_diem SET percentage = 50 WHERE user_id = 'salary-owner'; RAISE EXCEPTION 'FAIL closed allowance'; EXCEPTION WHEN raise_exception THEN ASSERT SQLERRM LIKE 'This month is closed%', SQLERRM; END;
  BEGIN DELETE FROM journey WHERE user_id = 'salary-owner' AND date = '2026-09-01'; RAISE EXCEPTION 'FAIL closed delete'; EXCEPTION WHEN raise_exception THEN ASSERT SQLERRM LIKE 'This month is closed%', SQLERRM; END;
  BEGIN UPDATE journey SET date = '2026-09-20' WHERE user_id = 'salary-owner' AND date = '2026-10-01'; RAISE EXCEPTION 'FAIL move into month'; EXCEPTION WHEN raise_exception THEN ASSERT SQLERRM LIKE 'This month is closed%', SQLERRM; END;
  BEGIN INSERT INTO journey(user_id, date, distance) VALUES ('salary-owner', '2026-11-01', 10), ('salary-owner', '2026-09-10', 10); RAISE EXCEPTION 'FAIL cross month'; EXCEPTION WHEN raise_exception THEN ASSERT SQLERRM LIKE 'This month is closed%', SQLERRM; END;
  ASSERT NOT EXISTS (SELECT 1 FROM journey WHERE user_id = 'salary-owner' AND date = '2026-11-01'), 'Partial trip inserted';
  BEGIN PERFORM payroll_generate('salary-owner', '2026-10', 'monthly', settings, '{"perDiemCents":0,"mileageCents":0}'); RAISE EXCEPTION 'FAIL stale travel'; EXCEPTION WHEN raise_exception THEN ASSERT SQLERRM LIKE 'Travel amounts changed%', SQLERRM; END;
  ASSERT NOT EXISTS (SELECT 1 FROM payroll_record WHERE month = '2026-10'), 'Failed generation closed month';
  bonus_id := payroll_generate('salary-owner', '2026-08', 'holiday', settings, travel);
  SELECT * INTO r FROM payroll_record WHERE id = bonus_id;
  ASSERT r.meal_cents = 0 AND r.per_diem_cents = 0 AND r.mileage_cents = 0 AND r.net_cents = 132950, 'Bonus allowances';
  INSERT INTO journey(user_id, date, distance) VALUES ('salary-owner', '2026-08-01', 10);
  BEGIN PERFORM payroll_generate('salary-owner', '2026-12', 'holiday', settings, travel); RAISE EXCEPTION 'FAIL duplicate annual bonus'; EXCEPTION WHEN unique_violation THEN NULL; END;
  PERFORM payroll_generate('salary-owner', '2026-12', 'christmas', settings, travel);
  PERFORM payroll_generate('salary-owner', '2027-08', 'holiday', settings, travel);
  BEGIN PERFORM payroll_pay('salary-other', payroll_id, 'salary', '2026-10-01', foreign_account, 1); RAISE EXCEPTION 'FAIL foreign owner'; EXCEPTION WHEN raise_exception THEN ASSERT SQLERRM = 'Payroll record not found', SQLERRM; END;
  BEGIN PERFORM payroll_pay('salary-owner', payroll_id, 'salary', '2026-10-01', foreign_account, 1); RAISE EXCEPTION 'FAIL foreign account'; EXCEPTION WHEN raise_exception THEN ASSERT SQLERRM = 'Choose one of your accounts', SQLERRM; END;
  ASSERT (SELECT count(*) FROM expense) = 0, 'Failed payment created expense';
  PERFORM payroll_pay('salary-owner', payroll_id, 'salary', '2026-10-01', NULL, 1);
  PERFORM payroll_pay('salary-owner', payroll_id, 'salary', '2026-10-01', account, 1);
  PERFORM payroll_pay('salary-owner', payroll_id, 'ss', '2026-10-20', account, 1);
  PERFORM payroll_pay('salary-owner', payroll_id, 'irs', '2026-10-20', account, 1);
  ASSERT (SELECT count(*) FROM expense) = 3, 'Duplicate expense';
  ASSERT (SELECT bool_and(created_at >= '2026-10-01' AND account_id = account AND NOT iva) FROM expense), 'Expense dates, account or IVA';
  ASSERT (SELECT sum(value) FROM expense) = 2474.44, 'Total outflow double counts deductions';
  SELECT expense_id INTO linked FROM payroll_payment WHERE record_id = payroll_id AND kind = 'salary' LIMIT 1;
  BEGIN UPDATE expense SET value = 1 WHERE id = linked; RAISE EXCEPTION 'FAIL direct expense edit'; EXCEPTION WHEN raise_exception THEN ASSERT SQLERRM LIKE 'This expense is linked%', SQLERRM; END;
  BEGIN DELETE FROM expense WHERE id = linked; RAISE EXCEPTION 'FAIL direct expense delete'; EXCEPTION WHEN raise_exception THEN ASSERT SQLERRM LIKE 'This expense is linked%', SQLERRM; END;
  BEGIN PERFORM payroll_apply('salary-other', payroll_id, 1, settings); RAISE EXCEPTION 'FAIL foreign update'; EXCEPTION WHEN raise_exception THEN ASSERT SQLERRM LIKE 'Payroll changed%', SQLERRM; END;
  settings := jsonb_set(settings, '{grossCents}', '200000');
  PERFORM payroll_apply('salary-owner', payroll_id, 1, settings);
  SELECT * INTO r FROM payroll_record WHERE id = payroll_id;
  ASSERT r.revision = 2 AND r.per_diem_cents = 9081 AND r.mileage_cents = 8800, 'Apply snapshot/revision';
  ASSERT (SELECT sum(value) * 100 FROM expense) = r.company_cents, 'Paid expense amounts not synced';
  ASSERT (SELECT count(*) FROM expense) = 3, 'Apply created duplicate expenses';
  BEGIN PERFORM payroll_apply('salary-owner', payroll_id, 1, settings); RAISE EXCEPTION 'FAIL stale revision'; EXCEPTION WHEN raise_exception THEN ASSERT SQLERRM LIKE 'Payroll changed%', SQLERRM; END;
  PERFORM payroll_unpay('salary-owner', payroll_id, 'irs');
  ASSERT (SELECT count(*) FROM expense) = 2 AND (SELECT count(*) FROM payroll_payment) = 2, 'Undo not atomic';
  PERFORM payroll_pay('salary-owner', payroll_id, 'irs', '2026-10-21', account, 2);
  INSERT INTO iva_quarter(user_id, year, quarter, status) VALUES ('salary-owner', 2026, 4, 'closed');
  BEGIN PERFORM payroll_apply('salary-owner', payroll_id, 2, jsonb_set(settings, '{grossCents}', '250000')); RAISE EXCEPTION 'FAIL closed IVA'; EXCEPTION WHEN raise_exception THEN ASSERT SQLERRM LIKE 'This quarter is closed%', SQLERRM; END;
  ASSERT (SELECT revision FROM payroll_record WHERE id = payroll_id) = 2, 'Partial payroll update after failed expense sync';
  BEGIN PERFORM payroll_unpay('salary-owner', payroll_id, 'irs'); RAISE EXCEPTION 'FAIL closed IVA undo'; EXCEPTION WHEN raise_exception THEN ASSERT SQLERRM LIKE 'This quarter is closed%', SQLERRM; END;
  ASSERT (SELECT count(*) FROM payroll_payment) = 3, 'Failed undo lost payment';
  DELETE FROM financial_account WHERE id = account;
  ASSERT (SELECT bool_and(account_id IS NULL) FROM expense), 'Account deletion lost historical payments';
  ASSERT (SELECT count(*) FROM payroll_payment) = 3, 'Account deletion erased payments';
  DELETE FROM "user" WHERE id = 'salary-owner';
  ASSERT NOT EXISTS (SELECT 1 FROM payroll_payment), 'User deletion left orphan payments';
END $$;
